// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  File = 2,
  FuncDecl = 3,
  Identifier = 4,
  ParameterList = 7,
  TypeExpr = 8,
  Block = 10,
  StructDecl = 11,
  StructPropDecl = 13,
  String = 16,
  Boolean = 17,
  Number = 18,
  BinaryExpression = 19
